title: Text Banner
status: done
context:
  text-banner-header: "That Supplement Show"
  text-banner-p: "Improving lives and inspiring others is at the heart of everything we do. Our new podcast is here to encourage mindful, vibrant living, with plenty of tips, interviews, and information to keep you healthy along the way."
